#!/usr/bin/env python3
"""
Updated on Tue Apr 07 2020
@maintainers: Viorela Ila, Max Revay, Jing Cheng, Stefan Williams, Tejaswi Digumarti
"""

import numpy as np
from turtlebot_landmark_slam.utils import RelativeLandmarkPositions 
from turtlebot_landmark_slam.utils import pi2pi


def ErrorFunction(solution_file, gt_file):
    """
    Calculates the error between ground truth data and the data obtained after SLAM
    :param solution_file: a .txt file containing the absolute positions of the landmarks as computed after SLAM
    :param gt_file: a .txt file containing the ground truth absolute positions of the landmarks
    :return : relative ground truth landmark positions - relative estimated landmark positions
    """
   
    landmark_pred = {}
    landmark_gt = {}

    # parse the txt files
    if solution_file.endswith('.txt') and gt_file.endswith('.txt'):
        f = open(solution_file, 'r')
        for line in f:
            line = line.strip()
            info = line.split(' ')
            if len(info) > 1 and info[0] == 'POINT2D':
                landmark_pred[int(info[1])] = [float(info[2]), float(info[3])]
        f.close()
           
        f = open(gt_file, 'r')
        for line in f:
            line = line.strip()
            info = line.split(' ')
            if len(info) > 1 and info[0] == 'POINT2D':
                landmark_gt[int(info[1])] = [float(info[2]), float(info[3])]
        f.close()

    # Compute positions of landmarks relative to the positions of another landmark
    landmark_error = []
    landmark_gt_ids = landmark_gt.keys()


    missed_lmks = []
    for landmark_id, _ in landmark_gt.items():
        if landmark_id not in landmark_pred:
            print(f"Ground truth lmk id {landmark_id} does not appear in your solution file!")
            missed_lmks.append(landmark_id)

    additional_lmks = []
    matched_mks = []

    for landmark_id, relative_pos in landmark_pred.items():
        if landmark_id not in landmark_gt_ids:
            additional_lmks.append(landmark_id)
            print(f"Your solution has lmk id {landmark_id} which does not occur in the ground truth")
        else:
            matched_mks.append(landmark_id)


    for i in range(0, len(matched_mks) - 1):
        lmk_id_1 = matched_mks[i]
        lmk_id_2 = matched_mks[i+1]

        predicted_pos_1 = [lmk_id_1, landmark_pred[lmk_id_1][0], landmark_pred[lmk_id_1][1]]
        gt_pos_1 = [lmk_id_1, landmark_gt[lmk_id_1][0], landmark_gt[lmk_id_1][1]]

        predicted_pos_2 = [lmk_id_2, landmark_pred[lmk_id_2][0], landmark_pred[lmk_id_2][1]]
        gt_pos_2 = [lmk_id_2, landmark_gt[lmk_id_2][0], landmark_gt[lmk_id_2][1]]

        landmarks_pred_rel = RelativeLandmarkPositions(predicted_pos_1,predicted_pos_2)
        landmarks_gt_rel = RelativeLandmarkPositions(gt_pos_1, gt_pos_2)

        landmark_error.append(np.array(landmarks_gt_rel) - np.array(landmarks_pred_rel))
    
    if len(landmark_pred) > 1:
        error_landmark = (1.0/(len(landmark_pred)-1))*np.linalg.norm(landmark_error)
    else:
        error_landmark = 0.
    # print 'Your Solution Error', errorLandmark
    
    return error_landmark


if __name__ == "__main__":
    import argparse
    import os

    parser = argparse.ArgumentParser(
                    prog='Evaluate Map',
                    description='Evaluates the POIN2D locations of landmarks against a ground truth file')
    parser.add_argument("--solution", help="Full path to your solution file as generated by map_writer.py", required=True)
    parser.add_argument("--gt", help="Full path to the ground truth file", required=True)

    args = parser.parse_args()

    file_solution = args.solution
    file_gt = args.gt

    if not os.path.exists(file_solution):
        raise FileNotFoundError(f"File solution does not exist at the given path {file_solution}")

    if not os.path.exists(file_gt):
        raise FileNotFoundError(f"File gt does not exist at the given path {file_gt}")


    error = ErrorFunction(file_solution, file_gt)
    print("Error:", error)
    

